### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by max-block** [MAIAN-tool/MAIAN#2]
```
maxblock@mbp tool (master)*$ python maian.py -s example_contracts/example_suicidal.sol KAI -c 0
Traceback (most recent call last):
  File "maian.py", line 53, in <module>
    import check_suicide
  File "/Users/maxblock/projects/tmp/MAIAN/tool/check_suicide.py", line 4, in <module>
    from execute_block import *
  File "/Users/maxblock/projects/tmp/MAIAN/tool/execute_block.py", line 5, in <module>
    from execute_instruction import *
  File "/Users/maxblock/projects/tmp/MAIAN/tool/execute_instruction.py", line 128
    global last_eq_step, last_eq_func
                                    ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by nusnikolic** [comment]
Fixed

**Comment by max-block** [comment]
The problem with tabs&spaces is fixed, but now there is another error:

```
(.venv) maxblock@mbp tool (master)*$ python maian.py -s example_contracts/example_suicidal.sol KAI -c 0

====================================================================================================
[ ] Compiling Solidity contract from the file example_contracts/example_suicidal.sol ... Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 98, in main
    compile_contract(args.soliditycode[0])
  File "/Users/maxblock/projects/tmp/MAIAN/tool/contracts.py", line 32, in compile_contract
    solo += l
TypeError: must be str, not bytes
```

**Comment by nusnikolic** [comment]
Code updated according to the solution provided by @cookedsteak (thanks!). 
@max-block, please confirm it works

**Comment by max-block** [comment]
The second error is fixed, now there is a new one:

```
(venv) maxblock@mbp tool (master)*$ python maian.py -s example_contracts/example_suicidal.sol KAI -c 0

====================================================================================================
[ ] Compiling Solidity contract from the file example_contracts/example_suicidal.sol ...  Done
[ ] Connecting to PRIVATE blockchain emptychain  . ESTABLISHED
[ ] Deploying contract .Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 120, in main
    if args.soliditycode:   contract_address = deploy_contract(args.soliditycode[1], MyGlobals.etherbase_account)
  File "/Users/maxblock/projects/tmp/MAIAN/tool/contracts.py", line 99, in deploy_contract
    s.run()
  File "/Users/maxblock/.pyenv/versions/3.6.4/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/Users/maxblock/projects/tmp/MAIAN/tool/contracts.py", line 115, in confirm_contract
    receipt = MyGlobals.web3.eth.getTransactionReceipt(transaction_creation_hash)
  File "/Users/maxblock/projects/tmp/MAIAN/tool/venv/lib/python3.6/site-packages/web3/eth.py", line 192, in getTransactionReceipt
    [transaction_hash],
  File "/Users/maxblock/projects/tmp/MAIAN/tool/venv/lib/python3.6/site-packages/web3/manager.py", line 96, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'unknown transaction'}
```

**Comment by 1522402210** [comment]
@nusnikolic 
python3 maian.py -c 0 -s example_contracts/example_suicidal.sol HyperLending

=========================================================================
[ ] Compiling Solidity contract from the file example_contracts/example_suicidal.sol ...  Done
[-] Contract HyperLending does NOT exist

**Comment by jinspiron** [comment]
@1522402210 Hi! I've installed all of the dependencies for MAIAN but for some reasonI still can't the program to work. 

`git clone https://github.com/MAIAN-tool/MAIAN.git`
`fatal: destination path 'MAIAN' already exists and is not an empty directory.`

and then when I try to check and see if the program is installed, I get this:

`python MAIAN.py`
`python: can't open file 'MAIAN.py': [Errno 2] No such file or directory`

What should I do?
